name: Continuous Integration and Deployment

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22

      - name: Install Dependencies and Build
        run: |
          cd client
          npm ci
          npm run build

  docker_push:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build docker image
        run: |
          cd client 
          docker build -t jpplay/vox-client .

      - name: Push docker image
        run: docker push jpplay/vox-client:latest

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: docker_push
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull jpplay/vox-client:latest

      - name: Run docker container
        run: |
          docker rm -f vox-client || true && \
          docker run -d -p 80:4000 --name vox-client jpplay/vox-client:latest
